name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Run
        run: ./hack/lint
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GO_VERSION:
          - 1.17
          - 1.18beta1
    env:
      GO_VERSION: ${{ matrix.GO_VERSION }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      -
        name: Run local
        run: |
          docker buildx bake binary
          ./bin/amd64variant
      - name: Build all
        run: docker buildx bake all-arch
